name: Build with ESP-IDF v4.4

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'

      
    
    - run: pwd
    - run: ls


    - name: Arduino build ESP32-C3
      uses: espressif/esp-idf-ci-action@main
      with:
        esp_idf_version: release-v4.4
        target: esp32c3
        command: "idf.py set-target esp32c3 && idf.py build"
        
    - run: ls ./build
    - run: ls ./build/partition_table
    - run: ls ./build/bootloader


            
    - uses: actions/upload-artifact@v2
      with:
        name: c.bin
        path:   build/app-template.bin
