name: Build with ESP-IDF v4.4

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'

      
    
    - run: pwd
    - run: ls



        
    - name: Arduino build ESP32
      uses: espressif/esp-idf-ci-action@main
      with:
        esp_idf_version: release-v4.4
        target: esp32
        command: "idf.py set-target esp32 && idf.py build"
        
        
    - run: ls ./build
    - run: ls ./build/partition_table
    - run: ls ./build/bootloader
    - run: pip install esptool

    - uses: actions/upload-artifact@v2
      with:
        name: esp32_partition_table.bin
        path:  /build/partition_table.bin


    - uses: actions/upload-artifact@v2
      with:
        name: esp32_bootloader.bin
        path:   /build/bootloader.bin
    
            
    - uses: actions/upload-artifact@v2
      with:
        name: esp32_app.bin
        path:   build/app-template.bin
        
        
    - name: Arduino build ESP32-C3
      uses: espressif/esp-idf-ci-action@main
      with:
        esp_idf_version: release-v4.4
        target: esp32c3
        command: "idf.py set-target esp32c3 && idf.py build"
        
        
    - uses: actions/upload-artifact@v2
      with:
        name: espc3_partition_table.bin
        path:  /build/partition_table.bin


    - uses: actions/upload-artifact@v2
      with:
        name: espc3_bootloader.bin
        path:   /build/bootloader.bin
    
            
    - uses: actions/upload-artifact@v2
      with:
        name: espc3_app.bin
        path:   build/app-template.bin
        
    - run : cd ./build
        
    - run: esptool.py --chip ESP32-C3 merge_bin -o merged-flash.bin @flash_args
    
    - uses: actions/upload-artifact@v2
      with:
        name: espc3_merged.bin
        path:   build/merged-flash.bin

        
    
        
